### ISSUE TITLE
Request for Documentation: Add company specific Root CA's

### ISSUE THREAD

**Issue by sambou90** [DelineaXPM/dsv-k8s#110]
**Problem**
Connection to Secret Server fails because of missing trusted Root CA:

2023/08/29 07:11:56 [DEBUG] grant response error:Post "https://swwpam.ch/SecretServer/.secretsvaultcloud.com/v1/token": tls: failed to verify certificate: x509: certificate signed by unknown authority

I guess I can set the company Root CA's over the optional ConfigMap section in values.yaml:

configmap:
  DSV_CERT:
  DSV_KEY:
  DSV_CREDENTIALS_JSON:
  DSV_SERVER_ADDRESS:
  DSV_DEBUG: 'true'
  
But I miss some documentation here. Maybe an example.

Thank you in advance for some hints or feedback regarding this topic.

**Comment by andrii-zakurenyi** [comment]
Hi @sambou90! Both Injector and Syncer from this repository are created to work only with [DevOps Secrets Vault (DSV)](https://docs.delinea.com/online-help/devops-secrets-vault/start.htm) and not with Secret Server.

**Comment by sambou90** [comment]
Hi @andrii-zakurenyi 
Thank you for your quick response. In the official docs regarding integrations it is written that the admission webhook supports Delinea Secret Server AND DSV: https://docs.delinea.com/online-help/integrations/ibm/redhat/openshift/index.htm
I would still appreciate an example on how to set Root CA's for secure communication to the DSV. I guess we switch to DSV if it is true that Secret Server do not support the admission webhook.

**Comment by sambou90** [comment]
Hi now reproduced the issue with DevOps Secrets Vault (DSV):

2023/08/29 13:37:41 [DEBUG] grant response error:Post "https://test.secretsvaultcloud.com/v1/token": tls: failed to verify certificate: x509: certificate signed by unknown authority

We have a transparent proxy between the pod and the internet, so I need to put our Proxy Root CA into the injector.

Thanks for any help.

**Comment by andrii-zakurenyi** [comment]
DSV is a cloud application and relies on Amazon-issued digital certificates. When communicating with DSV, the DSV Injector relies on default certificates detection provided by [Go](https://go.dev/) language.

For example for Linux it will try following paths:
```go
// Possible certificate files; stop after finding one.
var certFiles = []string{
	"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
	"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6
	"/etc/ssl/ca-bundle.pem",                            // OpenSUSE
	"/etc/pki/tls/cacert.pem",                           // OpenELEC
	"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7
	"/etc/ssl/cert.pem",                                 // Alpine Linux
}
```

**Comment by andrii-zakurenyi** [comment]
As I understand, you can override default location using `SSL_CERT_FILE` and `SSL_CERT_DIR`:

```go
const (
	// certFileEnv is the environment variable which identifies where to locate
	// the SSL certificate file. If set this overrides the system default.
	certFileEnv = "SSL_CERT_FILE"

	// certDirEnv is the environment variable which identifies which directory
	// to check for SSL certificate files. If set this overrides the system default.
	// It is a colon separated list of directories.
	// See https://www.openssl.org/docs/man1.0.2/man1/c_rehash.html.
	certDirEnv = "SSL_CERT_DIR"
)
```
src: https://github.com/golang/go/blob/master/src/crypto/x509/root_unix.go

**Comment by sambou90** [comment]
Hi @andrii-zakurenyi 
Thank you for your help, that actually worked!
