### ISSUE TITLE
Improve documentation (v1.2.2)

### ISSUE THREAD

**Issue by Tosta-Mista** [DelineaXPM/dsv-k8s#118]
Hello, 

I tried to follow your documentation, in order to install dsv-syncer and injector on a Kubernetes cluster (rke2). As we have our instance located in europe (tld = eu). 

Unfortunately, in the documentation there's no example to change the TLD so I decided to add it in my PR.

I also got a patch error (on the syncer side) if I didn't add a dummy value in the secret data, so I also modified this part in the documentation.

Thank you for the work you do and I hope my PR is done properly.

Best regards,

**Comment by sheldonhull** [comment]
fixed by 5e21066c8290072b74c370250be19b62c009c136
