### ISSUE TITLE
Username and Password Field is hardcoded in get-Secret.yml and update-secret.yml file

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/dsv-k8s#44]
**Description of the issue**

Username and Password Field is hardcoded in get-Secret.yml and update-secret.yml file

**Expected behaviour**

Credential is fetch from secure vault not hard coded. 

**Actual behavior**

Credential is hard coded

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/100804646/191777515-3b57b05c-07a3-4e4e-936d-4363644c9fdf.png)

**Comment by sheldonhull** [comment]
This is an example of schema that you'd use in Kubernetes, not a recommendation for local credential storage. This example is valid, and useful to keep for helping demonstrate how the resources in Kubernetes are supposed to have values configured to match to a DSV path and value in the data.
