### ISSUE TITLE
Password hard-coded in Example in Readme

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/dsv-k8s#45]
**Description of the issue**

Password hard-coded in Example in Readme

**Expected behavior**

Credential should be fetched from secure vault or other secure method

**Actual behavior**

Cred is hard coded. 

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/100804646/191778733-39cfc280-dead-431e-90ed-5d622ab35753.png)

**Comment by sheldonhull** [comment]
This is a valid example, showing how to use the product in Kubernetes, not a recommendation for any local service account credential storage.
