### ISSUE TITLE
Latest chart version image with problem

### ISSUE THREAD

**Issue by JulianPedro** [DelineaXPM/dsv-k8s#83]
### Environment

- Minikube v1.25.2 on Arch 22.0.0 (Tested with Docker and Virtualbox Driver)

### Problem

![image](https://user-images.githubusercontent.com/18649453/211650465-414df450-22f2-40cb-ab28-8335201889e4.png)

After updating the image repository to docker, installing chart has this problem. The version with the old repository (quay.io) works fine.

I think the image is the problem.

### Other related issue

![image](https://user-images.githubusercontent.com/18649453/211651336-34ea780c-5125-4879-bf6d-0b9bc5f84188.png)

We also use another way of using Delinea, related to kuberentes (Sidecar), the image was updated some time ago and changed from amd64 to arm64, can you fix that?

**Before this update the latest version was amd64 and worked relatively well.**

**Comment by sheldonhull** [comment]
First off, I'm sorry there was a delay in responding to you. I didn't see any notification of this new issue being reported! Most of the requests for support come through our support team. I'll see if I can improve this so you get a response in the future much sooner.

I think you might have gotten help on this but can you confirm by closing as resolved or update here if you still need help? The dsv-k8s-controller project is a different one from this, but. think you'll find the latest `amd64` build is on latest tag now in dockerhub.

We'll migrate that image eventually over to the new [DelineaXPM org in docker](https://hub.docker.com/u/delineaxpm) org in docker too, but haven't had a chance to do that yet.

**Comment by sheldonhull** [comment]
related AB#483421 - I've identified a fix for the image not finding the injector/syncer and should have out shortly.
