### ISSUE TITLE
Invalid Memory Address (thycotic/dsv-k8s-controller)

### ISSUE THREAD

**Issue by JulianPedro** [DelineaXPM/dsv-k8s#90]
Hello guys!

Guys, we use your integration for kubernetes (sidecar) which is in the repository https://hub.docker.com/r/thycotic/dsv-k8s-controller (https://docs.thycotic.com/dsv/current/usage/integrations/kubernetes/kubernetes-sidecar/broker.md), some time ago we reported a problem that the broker restarted from time to time, it was updated on dockerhub with the solution, but with an arm64 version, now it's updated to amd64 again, but the restart problem is back, follow the error log, you can do it Help us?

```
time="2023-01-30T18:57:34Z" level=error msg="Error getting pod" error=EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8d0fc5]

goroutine 30 [running]:
container-go/pkg/pods.NewPodRegistry.func1({0x7ffeca2a40bf, 0xd}, 0xc000237550, 0x0?, 0x0?, 0x0?)
	/go/src/container-go/pkg/pods/registry.go:63 +0x105
created by container-go/pkg/pods.NewPodRegistry
	/go/src/container-go/pkg/pods/registry.go:55 +0x36a
```

Another thing we wanted was the availability of this code on Github so that it would be easier for us to report problems and/or solutions.

Thanks!

**Comment by sheldonhull** [comment]
I'm on the dsv team and I'll reach out to see what's happening there. Appreciate you opening this issue!

**Comment by JulianPedro** [comment]
@sheldonhull I really appreciate your attention! If you can reinforce the creation of the public repository it would be very good, because we could open PR's to solve the problems! Thank you very much!

**Comment by sheldonhull** [comment]
Also we definitely want to publish that but there are some internal changes needed before we publish it. I don’t have an eta but am following up with the team today on this. It would be great if you’d open a support case so someone is assigned and can update you directly.

**Comment by tdillenbeck** [comment]
@JulianPedro, thanks for the report here.  We are working on a release for this issue.  We plan to have it out this week, hopefully tomorrow.  

I'll update here when it's out.

E porque eu quero practicar escrever em português: Oi, tudo bom! Eu não encontro muitos programmers do Brasil.  Obrigado por usar DSV!

**Comment by JulianPedro** [comment]
Haha :)
Muito obrigado pessoal!

@tdillenbeck and @sheldonhull

**Comment by tdillenbeck** [comment]
The new images have been pushed!  Try it out and let us know here if you have more issues with panics.

**Comment by JulianPedro** [comment]
@tdillenbeck The new image is arm64 architecture, it should be amd64.

**Comment by tdillenbeck** [comment]
@JulianPedro It is now amd64.  I am working to make sure this doesn't happen again!

**Comment by sheldonhull** [comment]
@JulianPedro marking as closed. Feel free to reopen the issue if the same issues pops up or open a new one for anything else you have questions on. I setup some additional notifications so I see your post quicker next time 😉 Cheers.
